# Generated by Django 2.1.2 on 2020-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190827_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lesson',
            field=models.IntegerField(choices=[(1, '※基礎程式設計：使用Scratch3.X'), (2, '※進階程式設計：使用Scratch3.X')], default=2, verbose_name='課程名稱'),
        ),
    ]
